build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (777) 265-3765
    - (777) 734-8371